name: Security and Deployment

on:
  push:
    branches:
      - main
      - gh-pages
  pull_request:
    branches:
      - main
      - gh-pages
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run audit
      run: npm audit --audit-level=high

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL analysis
      uses: github/codeql-action/analyze@v2

  deploy-gh-pages:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/gh-pages'

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Build and deploy
      run: |
        npm install
        npm run build
        git add .
        git commit -m "Deploy updates"
        git push origin gh-pages
